Blog.WEB/Blog.WEB/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Blog.BLL.DTO;
using Blog.BLL.Interfaces;
using Blog.BLL.Services;
using Blog.Models;
using PagedList;

namespace Blog.WEB.Controllers
{
    public class PostController : BaseController
    {
        IServiceCreator service;
        
        public PostController()
        {
            service = new ServiceCreator("Blog");
            ViewBag.PageSize = pageSize;
        }

        int pageSize = 2; 
        public ActionResult Index(int? blogId, int? tagId, int page = 1)
        {
            IEnumerable<PostModel> posts;
            ViewBag.Page = page;
            if (blogId != null)
            {
                var p = service.postService.GetByBlogId((int)blogId);
                posts = mapperBusinessToView.Map<IEnumerable<PostModel>>(p);
                return View(posts.ToPagedList(page, pageSize));
            }
            if (tagId != null)
            {
                ViewBag.tag = "tag";
                ViewBag.tagId = tagId;

                var p = service.postService.GetByTagId((int)tagId);
                posts = mapperBusinessToView.Map<IEnumerable<PostModel>>(p);
                return View(posts.ToPagedList(page,pageSize));
            }

            return View("Error");
        }

        // GET: Post/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDTO postDTO = service.postService.Get(id);
            if (postDTO == null)
            {
                return HttpNotFound();
            }
            PostModel post = mapperBusinessToView.Map<PostModel>(postDTO);
            return View(post);
        }

        // GET: Post/Create
        [Authorize]
        public ActionResult Create()
        {
            IEnumerable<BlogDTO> b = service.blogService.GetByName(User.Identity.Name);
            return View(mapperBusinessToView.Map<IEnumerable<BlogModel>>(b));
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,DateTime,Body,BlogID")] PostModel post, string tags)
        {
            if (ModelState.IsValid)
            {

                service.postService.Create(mapperViewToBusiness.Map<PostDTO>(post),tags);
                return RedirectToAction("Index", new { blogId = post.BlogID });
            }

            return View(post);
        }

        // GET: Post/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDTO postDTO = service.postService.Get(id);
            if (postDTO == null)
            {
                return HttpNotFound();
            }
            PostModel post = mapperBusinessToView.Map<PostModel>(postDTO);
            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,DateTime,Body,BlogID")] PostModel post)
        {
            if (ModelState.IsValid)
            {
                service.postService.Modify(mapperViewToBusiness.Map<PostDTO>(post));
                return RedirectToAction("Details", new { id = post.ID });
            }
            return View(post);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddComment([Bind(Include = "ID,DateTime,Body,UserID,PostID")] CommentModel comment)
        {
            if (ModelState.IsValid)
            {
                service.commentService.Create(mapperViewToBusiness.Map<CommentDTO>(comment));
                return RedirectToAction("Details", new { id = comment.PostID });
            }
            return View();
        }
        // GET: Post/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PostDTO postDTO = service.postService.Get(id);
            if (postDTO == null)
            {
                return HttpNotFound();
            }
            PostModel post = mapperBusinessToView.Map<PostModel>(postDTO);
            return View(post);
        }

        // POST: Post/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            service.postService.Delete(id);
            return RedirectToAction("Index", "Blogs");
        }
        [Authorize]
        [HttpPost, ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCommentConfirmed(int id, int postID)
        {
            service.commentService.Delete(id);
            return RedirectToAction("Index", "Blogs");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                service.postService.Dispose();
                service.blogService.Dispose();
                //postService.Dispose(disposing);
            }
            base.Dispose(disposing);
        }
    }
}

Blog.WEB/Blog.WEB/Controllers/SearchController.cs
using AutoMapper;
using Blog.BLL.DTO;
using Blog.BLL.Interfaces;
using Blog.BLL.Services;
using Blog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.WEB.Controllers
{
    public class SearchController : BaseController
    {
        IServiceCreator service;

        public SearchController()
        {
            service = new ServiceCreator("Blog");
        }
        // GET: Search
        public ActionResult Index(string word,int page=1)
        {
            var blogDTO = service.blogService.GetAll();
            List<PostDTO> postsDTO = new List<PostDTO>();
            foreach (var b in blogDTO)
                foreach (var p in b.Posts)
                    if (p.Title.Contains(word) || p.Body.Contains(word))
                        postsDTO.Add(p);
                    else foreach (var tag in p.Tags)
                            if (tag.Tag == word)
                                postsDTO.Add(p);
            var posts = mapperBusinessToView.Map<List<PostModel>>(postsDTO);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            ViewBag.Search = word;
            return View("Index",posts);
        }
        int pageSize = 3;
        // GET: Search/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Search/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Search/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Search/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Search/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Blog.WEB/Blog.WEB/Controllers/UsersController.cs
using AutoMapper;
using Blog.BLL.DTO;
using Blog.BLL.Interfaces;
using Blog.BLL.Services;
using Blog.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Blog.WEB.Controllers
{
    public class UsersController : BaseController
    {
        IServiceCreator service;
        int pageNumber = 1;
        int pageSize = 3;
        public UsersController()
        {
            service = new ServiceCreator("Blog");
        }
        // GET: Users
        public ActionResult Index()
        {
            var users = service.userService.GetAll();
            return View("ListUsers", mapperBusinessToView.Map<IEnumerable<UserModel>>(users).ToPagedList(pageNumber, pageSize));
        }


       [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BlockUnblockUser(string id)
        {
            service.userService.BlockUnblock(id);

            return RedirectToAction("Details", new { id });
        }
        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null || id == "")
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            UserDTO userDTO = service.userService.GetById(id);
            if (userDTO == null)
                return HttpNotFound();
            UserModel user = mapperBusinessToView.Map<UserModel>(userDTO);
            return View(user);
        }

        // GET: Users/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Users/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Users/Edit/5
        [Authorize(Roles = "admin")]
        public ActionResult Edit(string id)
        {
            if (id == null || id == "")
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            UserDTO userDTO = service.userService.GetById(id);
            List<string> userRoles = service.roleService.GetRolesByUserId(id);
            var allRoles = service.roleService.GetAll();
            Dictionary<string, bool> dictionary = new Dictionary<string, bool>();
            foreach (var role in allRoles)
                dictionary.Add(role, userRoles.Contains(role));

            //foreach (var item in dictionary.Keys)
            //{

            //}
            ViewBag.roles = dictionary;

            if (userDTO == null)
                return View("Error");
            UserModel user = mapperBusinessToView.Map<UserModel>(userDTO);
            return View(user);
        }

        // POST: Users/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Edit(UserModel user, string[] selectedRoles, HttpPostedFileBase uploadImage)
        {
            //try
            //{
            if (user == null)
                return View("Error");
            if (selectedRoles == null)
                selectedRoles = new string[] { "user" };
            byte[] imageData = null;
            using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            {
                imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            }
            user.Photo = imageData;
            //service.userService.Modify(mapperViewToBusiness.Map<UserDTO>(user));
            service.roleService.UpdateListRoles(selectedRoles, user.Id);
            service.userService.Modify(mapperViewToBusiness.Map<UserDTO>(user));
            return RedirectToAction("Index");
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Users/Delete/5
        [Authorize(Roles = "admin")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Users/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Blog.WEB/Blog.WEB/Views/Shared/DisplayPost.cshtml
@model IEnumerable<Blog.Models.PostModel>
@{
    ViewBag.RangeColor = new string[] { "danger", "primary", "info", "success", "warning", "default" };
    ViewBag.rand = new Random();
}
@foreach (var item in Model)
{
    <h2>@Html.ActionLink(item.Title, "Details", new { id = item.ID })</h2>
    <h5><span class="glyphicon glyphicon-time"></span> Post by @item.Blog.Bloger.UserName, on @item.DateTime.Month @item.DateTime.Day, @item.DateTime.Year.</h5>
    <h5>
        @foreach (var tag in item.Tags)
        {
            <span class="label label-@ViewBag.RangeColor[ViewBag.rand.Next(5)]">@Html.ActionLink(@tag.Tag, "Index", new { tagId = tag.ID })</span>
        }
    </h5>
    <br>
    <p>@Html.DisplayFor(modelItem => item.ShortBody)</p>
    <p>@Html.ActionLink("Read More ->", "Details", new { id = item.ID }, new { @class = "btn btn-primary glyphicon-arrow-right" })</p>
    <br><br>
}

Blog.WEB/Blog.WEB/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Войти", "Login", "Account")</li>
                            <li>@Html.ActionLink("Регистрация", "Register", "Account")</li>
                        }
                        else
                        {
                            <li>
                                <a>Привет @User.Identity.Name</a>
                            </li>
                            <li>@Html.ActionLink("Выход", "Logout", "Account")</li>
                        }

                    </ul>
                </div>
            </div>
        </div>*@
    <div class="row">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Blogs", new { area = "" }, new { @class = "navbar-brand" })
        </div>
    </div>
    <br />
    <div class="container-fluid">

        <div class="row content">
            <div class="col-sm-3 sidenav">
                @*<h4>@Html.ActionLink("MAP's Blog", "Index", "Blogs", new { area = "" }, new { @class = "navbar-brand" })</h4>*@

                <ul class="nav nav-pills nav-stacked">
                    <li>@Html.ActionLink("Home", "Index", "Blogs")</li>

                    <li>@Html.ActionLink("All users", "Index", "Users")</li>
                    <li><a href="#section2">My blogs</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Create blog", "Create", "Blogs", new { id = User.Identity.GetUserId() }, null)</li>
                        <li>@Html.ActionLink("Create post", "Create", "Post")</li>
                    }
                </ul><br>
                <ul class="nav nav-pills nav-stacked">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Account")</li>
                        <li>@Html.ActionLink("Register", "Register", "Account")</li>
                    }
                    else
                    {
                        <li>
                            <a>Hello @User.Identity.Name</a>
                        </li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }

                </ul>
                @using (Html.BeginForm("Index", "Search"))
                {
                    <div class="input-group">
                        @Html.Editor("word", new { htmlAttributes = new { @class = "form-control", placeholder = "Search Blog.." } })
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search">
                                </span>
                            </button>
                        </span>
                    </div>
                }

            </div>
            @*<div class="container body-content">*@
            <div class="col-sm-9">
                @RenderBody()
            </div>
            <hr />

        </div>
    </div>
    <br />
    <div class="row">
        <footer>
            <p>&copy; @DateTime.Now.Year - My Blogs Site</p>
        </footer>
    </div>


</body>
</html>